name: pipeline-financeiro

services:
  kafka-init:
    container_name: kafka-init
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    volumes:
      - ./docker_scripts/kafka_init.sh:/scripts/kafka_init.sh
    command: ["/bin/bash", "/scripts/kafka_init.sh"]
    restart: on-failure
    networks:
      - 'sparknet'

  kafka-1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-1
    restart: on-failure
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-1:9092,EXTERNAL://localhost:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - 'sparknet'

  kafka-2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-2
    restart: on-failure
    ports:
      - "29093:29092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-2:9092,EXTERNAL://localhost:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - 'sparknet'

  kafka-3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-3
    restart: on-failure
    ports:
      - "29094:29092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-3:9092,EXTERNAL://localhost:29094'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - 'sparknet'

  python-producer-app:
    build: ./producer-app
    container_name: python-producer-app
    restart: on-failure
    depends_on: 
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
    networks:
      - 'sparknet'


  spark-master:
    image: public.ecr.aws/bitnami/spark:3.5.0
    container_name: spark-master
    restart: on-failure
    ports:
      - '8080:8080'
      - '7077:7077'
    environment:
      SPARK_MODE: 'master'
      SPARK_SUBMIT_OPTS: > 
        --packages 
        org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,
        org.apache.hadoop:hadoop-aws:3.3.4,
        com.amazonaws:aws-java-sdk-bundle:1.12.262,
        org.apache.hadoop.fs.s3a.S3AFileSystem
    networks:
      - 'sparknet'

  spark-worker:
    image: public.ecr.aws/bitnami/spark:3.5.0
    restart: on-failure
    deploy:
      replicas: 3
    environment:
      SPARK_MODE: 'worker'
      SPARK_MASTER_URL: 'spark://spark-master:7077'
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G
      SPARK_SUBMIT_OPTS: > 
        --packages 
        org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,
        org.apache.hadoop:hadoop-aws:3.3.4,
        com.amazonaws:aws-java-sdk-bundle:1.12.262,
        org.apache.hadoop.fs.s3a.S3AFileSystem
    depends_on:
      - spark-master
    networks:
      - 'sparknet'

  jupyter-spark:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: jupyter-spark
    ports:
      - '8888:8888' 
      - '4040:4040'
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      JUPYTER_TOKEN: '1234'
    volumes:
      - ./notebooks:/home/jovyan/work
    env_file:
      - .env
    networks:
      - 'sparknet'

  spark-consumer-app:
    build: ./consumer-app
    container_name: spark-consumer-app
    tty: true
    depends_on: 
      - spark-master
      - kafka-1
      - kafka-2
      - kafka-3
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - SAVE_TO_S3=false
    env_file:
      - .env
    networks:
      - 'sparknet'

networks:
  sparknet:
    driver: bridge 