FROM public.ecr.aws/bitnami/spark:3.5.0

# Change user to root to install libraries and configure folders
USER root

WORKDIR /consumer-app
COPY . .
RUN pip install -r requirements.txt

RUN chmod -R 755 /consumer-app

# Start the script automatically
CMD ["python", "-u", "consumer.py"]